### ISSUE TITLE
Keras Implementaion of CAMERAS

### ISSUE THREAD

**Issue by sub1120** [VisMIL/CAMERAS#1]
Hello friend,
I want to use **CAMERAS** for Keras models, can you provide code for implementation in **Tensorflow Keras** early.

Thank you.

**Comment by VisMIL** [comment]
Hello,

We are hopeful to push the first version in a week. Stay tuned. 

Regards,

**Comment by sub1120** [comment]
Okay I will wait for it. If I use CAMERAS in my project, I will make sure to cite your publication. 

Thanks for reply.

**Comment by sub1120** [comment]
Hey @VisMIL , 

Will you update the same repository for **CAMERAS Keras** version or will create another repository for it.

**Comment by tansel** [comment]
Looking forward to it as well!

**Comment by VisMIL** [comment]
Hi, 

The new code will be released here. It is in the final stages of refactoring and after performing few tests, we will upload the first version by tomorrow. 

Regards,

**Comment by sub1120** [comment]
Thanks @VisMIL, I am already excited to use it.

**Comment by francismontalbo** [comment]
@VisMIL  we are all excited for that! Thank you so much!

**Comment by AsimJalwana** [comment]
We have just released the first version. Hope you find it helpful.

**Comment by VisMIL** [comment]
We have just released the first version. Hope you all find it helpful.
