### ISSUE TITLE
about 他和

### ISSUE THREAD

**Issue by IvanWZH** [VisMIL/CAMERAS#2]

**Comment by IvanWZH** [comment]
the evaluation method is not in the open-source code， would you like to show the evaluation code

**Comment by ericotjo001** [comment]
Yes, please, is it possible to open source the evaluation?

**Comment by VisMIL** [comment]
Sorry for catching up late. Sorry, We will include it as soon as we find time. It is a straight forward implementation, feel free to give it a try. Thanks.
