### ISSUE TITLE
Please add some license

### ISSUE THREAD

**Issue by sub1120** [VisMIL/CAMERAS#3]
Could you please add some license to this repository, so others can use, modify, and redistribute the code. eg. GPL V3

[Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by sub1120** [comment]
please look into this, it will be helpful for opensource community

**Comment by VisMIL** [comment]
Thank you for the suggestion. License has been included. Enjoy 😃

**Comment by sub1120** [comment]
Thanks @VisMIL
