### ISSUE TITLE
Input image upsampling in Keras implementation  

### ISSUE THREAD

**Issue by keertika-11** [VisMIL/CAMERAS#5]
Hi, in the paper it is mentioned that the input image is Upsampled but in the keras implementation it isn't possible to send an Image with a size greater than (224,224). Can you please provide a clear explanation if the Inputs should be Upsampled ?

**Comment by VisMIL** [comment]
Hi, You can try to redefine the input layer of model in Keras. This can be seen 40-42 in CAMERAS/KerasMap/CAMERASKeras.py and hence that will suffice. Please share if you feel like discussing more.
